import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Chart, Metric } from './LibraryWidgets';
import FocalChart, { focalDistribution, focalLabels, type FocalData } from './FocalChart';
import Comparison from './Comparison';
import UsageNotice from './UsageNotice';
import { Aperture, ArrowLeft, Camera, Check, ChevronRight, Database, FolderPlus, FolderOpen, HardDrive, Image as ImageIcon, LayoutDashboard, LoaderCircle, LogOut, Network, Pause, Play, RefreshCw, Search, Settings, Shuffle, SlidersHorizontal, Video, X, AlertCircle, Trash2, Square, Download } from 'lucide-react';

declare global { interface Window { __LENS_TOKEN__?: string } }
type Mode = 'equivalent' | 'native';
type Filters = { mode: Mode; cameras: string[]; lenses: string[]; focals: number[]; focal_bins: number[]; months: string[]; roots: number[]; kinds: string[]; missing: string[]; search: string };
type Group = { value: string | number; count: number; bytes: number };
type Asset = { id:number; relpath:string; kind:string; ext:string; size:number; camera:string|null; lens:string|null; focal_native:number|null; focal_equiv:number|null; focal_source:string|null; taken_at:string|null; time_source:string|null; aperture:number|null; shutter:string|null; iso:number|null; width:number|null; height:number|null; duration:number|null; codec:string|null; metadata_status:string; metadata_error:string|null; preview_status:string; preview_error:string|null; playback_status:string; availability?:string; root_label?:string; thumbnail_url:string; stream_url:string|null; metadata?:Record<string,unknown> };
type Root = { id:number; label:string; path:string; status:string; error:string|null; file_count:number; last_scan:string|null };
type Job = { id:string; root_id:number; root_label:string; status:string; phase:string; processed:number; total:number; enumerated:number; errors:number; message:string|null };
type Connection = { id:string; name:string; url:string; remembered?:boolean };
type Stats = { summary:{ count:number; bytes:number; photos:number; videos:number }; cameras:Group[]; lenses:Group[]; focals:Group[]; months:Group[]; missing:Record<string,{count:number;bytes:number}>; inventory:{kind:string;count:number;bytes:number}[]; states:{metadata_status:string;preview_status:string;count:number}[] };
const blank = (mode:Mode='equivalent'):Filters => ({mode,cameras:[],lenses:[],focals:[],focal_bins:[],months:[],roots:[],kinds:[],missing:[],search:''});
const num = (n:number|null|undefined) => (n || 0).toLocaleString('zh-CN');
const bytes = (n:number=0) => n >= 1024**3 ? (n/1024**3).toFixed(2)+' GB' : n >= 1024**2 ? (n/1024**2).toFixed(1)+' MB' : (n/1024).toFixed(1)+' KB';
const statusNames:Record<string,string> = {new:'未扫描',online:'在线',offline:'离线',error:'异常',permission_denied:'无权限',scanning:'扫描中',interrupted:'扫描未完成',queued:'等待中',running:'处理中',paused:'已暂停',cancelled:'已取消',completed:'已完成',failed:'读取失败',ok:'已读取',pending:'待处理',ready:'已生成',evicted:'缓存已清理',available:'文件可用',source_missing:'原片不存在',library_offline:'图库离线',unknown:'未验证',browser_candidate:'可尝试浏览器播放',unsupported:'当前浏览器可能不支持',image_preview:'图片预览',enumerate:'枚举文件',metadata:'读取元数据',preview:'生成预览',complete:'完成'};
const missingNames:Record<string,string> = {camera:'相机',lens:'镜头',focal:'焦距',time:'拍摄时间',any:'缺少任一字段'};

async function request<T=any>(url:string, token:string, body?:unknown, method?:string, signal?:AbortSignal):Promise<T> {
  const response = await fetch(url,{signal,method:method || (body !== undefined?'POST':'GET'),headers:{...(token?{Authorization:`Bearer ${token}`} : {}),...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined});
  if (!response.ok) { let detail; try { detail=(await response.json()).detail; } catch { detail=response.statusText; } throw Object.assign(new Error(typeof detail==='string'?detail:JSON.stringify(detail)),{status:response.status}); }
  return response.json();
}

function Photo({item,url,token,onClick}:{item:Asset;url:(path:string)=>string;token:string;onClick:()=>void}) {
  const [src,setSrc]=useState(''),[error,setError]=useState(false);
  useEffect(()=>{let valid=true,objectUrl=''; const controller=new AbortController();setSrc('');setError(false);
    if(['failed','permission_denied'].includes(item.preview_status)){setError(true);return;}
    fetch(url(item.thumbnail_url),{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.blob();}).then(blob=>{objectUrl=URL.createObjectURL(blob);if(valid)setSrc(objectUrl);}).catch(e=>{if(e.name!=='AbortError'&&valid)setError(true);});
    return ()=>{valid=false;controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};
  },[item.id,item.thumbnail_url,item.preview_status,url,token]);
  return <button className="photo" onClick={onClick}><div className="photo-image">{src?<img src={src} alt={item.relpath} loading="lazy"/>:error?<div className="photo-unavailable"><ImageIcon size={27}/><span>暂无可用预览</span><small>点击查看元数据和原因</small></div>:<LoaderCircle className="spin"/>}<span className="format">{item.kind==='video'&&<Video size={11}/>} {item.ext.toUpperCase()}</span></div><div className="photo-caption"><strong title={item.relpath}>{item.relpath.split('/').pop()}</strong><span>{item.camera || '相机信息缺失'}</span></div></button>;
}

export default function App(){
  const desktopToken=window.__LENS_TOKEN__ || '';
  const [token,setToken]=useState(desktopToken || sessionStorage.getItem('lens-session') || '');
  const [nativePlayback,setNativePlayback]=useState(false),[inlineUnsupported,setInlineUnsupported]=useState(false);
  const [desktop,setDesktop]=useState(!!desktopToken),[connections,setConnections]=useState<Connection[]>([]),[current,setCurrent]=useState<Connection|null>(null);
  const [page,setPage]=useState('overview'),[filters,setFilters]=useState<Filters>(blank()),[stats,setStats]=useState<Stats|null>(null),[roots,setRoots]=useState<Root[]>([]),[jobs,setJobs]=useState<Job[]>([]);
  const [items,setItems]=useState<Asset[]>([]),[total,setTotal]=useState(0),[refresh,setRefresh]=useState(0),[sample,setSample]=useState(0),[sampling,setSampling]=useState(true),[offset,setOffset]=useState(0);
  const [connected,setReady]=useState(false),[auth,setAuth]=useState(false),[setup,setSetup]=useState(false),[password,setPassword]=useState(''),[setupCode,setSetupCode]=useState('');
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[info,setInfo]=useState<any>(null);
  const [localNoticeAccepted,setLocalNoticeAccepted]=useState<boolean|null>(null);
  const ready=connected && info?.usage_notice_accepted !== false && (!desktop || localNoticeAccepted === true);
  const [detail,setDetail]=useState<Asset|null>(null),[detailImage,setDetailImage]=useState(''),[videoUrl,setVideoUrl]=useState(''),[videoError,setVideoError]=useState('');
  const [dialog,setDialog]=useState<'root'|'nas'|null>(null),[path,setPath]=useState(''),[label,setLabel]=useState(''),[directories,setDirectories]=useState<any>(null),[nasName,setNasName]=useState(''),[nasUrl,setNasUrl]=useState('');
  const [cacheLimit,setCacheLimit]=useState('2048');
  const cacheDraftRevision=useRef(0);
  const [remember,setRemember]=useState(true),[focalData,setFocalData]=useState<FocalData|null>(null);
  const restored=useRef(false);
  const [connectRevision,setConnectRevision]=useState(0);
  const connectionKey=current?.id || 'local';
  const prefix=current?`/api/remote/${current.id}`:'';
  const url=useCallback((path:string)=>prefix+path,[prefix]);
  const api=useCallback(<T=any,>(path:string,body?:unknown,method?:string,signal?:AbortSignal)=>request<T>(url(path),token,body,method,signal),[url,token]);
  const local=useCallback(<T=any,>(path:string,body?:unknown,method?:string)=>request<T>(path,token,body,method),[token]);
  const revision=useRef(0);
  const act=async(action:()=>Promise<unknown>,message?:string)=>{setBusy(true);setError('');try{await action();setRefresh(v=>v+1);if(message)setNotice(message);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const switchLibrary=(connection:Connection|null)=>{revision.current++;setConnectRevision(v=>v+1);setCurrent(connection);if(desktop)local('/api/desktop/preferences',{last_connection:connection?.id||null},'PUT').catch(()=>{});setFocalData(null);setReady(false);setAuth(false);setStats(null);setItems([]);setRoots([]);setJobs([]);setDetail(null);setInfo(null);setFilters(blank());setPage('overview');setError('');setNotice('');setPassword('');setSetupCode('');setOffset(0);};

  useEffect(()=>{request('/api/health','').then(h=>setDesktop(h.desktop)).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(desktop&&token&&localNoticeAccepted===true)local<Connection[]>('/api/connections').then(async rows=>{setConnections(rows);if(!restored.current){restored.current=true;const seq=revision.current;const pref=await local('/api/desktop/preferences');if(seq!==revision.current)return;const selected=rows.find(c=>c.id===pref.last_connection&&c.remembered);if(selected)switchLibrary(selected);}}).catch(e=>setError(e.message));},[desktop,token,refresh,local,localNoticeAccepted]);
  useEffect(()=>{let valid=true;if(desktop&&token)local('/api/info').then(value=>{if(valid){setNativePlayback(!!value.native_player_available);setLocalNoticeAccepted(value.usage_notice_accepted!==false);}}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};},[desktop,token,local,connectRevision]);
  useEffect(()=>{let valid=true;setReady(false);setInfo(null);api('/api/health').then(async health=>{if(!valid)return;if(health.api_version!==1)throw new Error('服务端接口版本不兼容，请更新客户端和服务端');setSetup(health.setup_required);try{const i=await api('/api/info');if(valid){setInfo(i);setCacheLimit(String(Math.round(i.cache.limit_bytes/1024**2)));setReady(true);setAuth(false);}}catch(e:any){if(valid){if(e.status===401)setAuth(true);else setError(e.message);}}}).catch(e=>{if(valid)setError(e.message);});return ()=>{valid=false;};},[api,connectionKey,token,connectRevision]);
  useEffect(()=>{if(!ready)return;let valid=true;const update=()=>Promise.all([api<Root[]>('/api/roots'),api<Job[]>('/api/jobs')]).then(([r,j])=>{if(valid){setRoots(r);setJobs(j);}}).catch(e=>{if(valid){setError(e.message);if(e.status===401){setReady(false);setAuth(true);}}});update();const timer=setInterval(update,2000);return()=>{valid=false;clearInterval(timer);};},[api,ready,refresh]);
  useEffect(()=>{if(!ready||page!=='settings')return;let valid=true;const draftRevision=cacheDraftRevision.current;api('/api/info').then(value=>{if(valid){setInfo(value);if(cacheDraftRevision.current===draftRevision)setCacheLimit(String(Math.round(value.cache.limit_bytes/1024**2)));}}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};},[api,ready,page]);
  const download=useCallback(async(path:string,name:string)=>{const r=await fetch(path,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('导出失败，请确认比对已完成');const blob=await r.blob();const link=document.createElement('a');const object=URL.createObjectURL(blob);link.href=object;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(object),1000);},[token]);
  const scanning=jobs.some(j=>['running','queued'].includes(j.status));
  const jobStamp=jobs.map(j=>`${j.id}:${j.status}:${j.phase}`).join('|');
  useEffect(()=>{if(!ready)return;let valid=true;const controller=new AbortController();api<Stats>('/api/stats',filters,undefined,controller.signal).then(summary=>{if(valid){setStats(summary);setFocalData(focalDistribution(summary.focals.map(row=>({...row,value:Number(row.value)}))));}}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;controller.abort();};},[api,filters,ready,refresh,jobStamp]);
  useEffect(()=>{if(!ready)return;let valid=true;const controller=new AbortController();setLoading(true);api<{items:Asset[];total:number}>('/api/assets/query',{filters,limit:24,offset,random:sampling},undefined,controller.signal).then(value=>{if(valid){setItems(value.items);setTotal(value.total);}}).catch(e=>{if(valid)setError(e.message);}).finally(()=>{if(valid)setLoading(false);});return()=>{valid=false;controller.abort();};},[api,filters,ready,refresh,sample,sampling,offset,jobStamp]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{if(!detail)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setDetail(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[detail]);
  useEffect(()=>{if(!detail)return;let valid=true,objectUrl='';setDetailImage('');setVideoUrl('');setVideoError('');setInlineUnsupported(false);
    if(detail.kind==='video'){
      const probe=document.createElement('video');
      const type=detail.codec==='h264'?'video/mp4; codecs="avc1.42E01E"':detail.codec==='hevc'?'video/mp4; codecs="hvc1.1.6.L93.B0"':null;
      if(type&&!probe.canPlayType(type)){setInlineUnsupported(true);setVideoError('当前内嵌播放器不支持此视频编码。已显示封面；桌面端可使用下方原生播放器，原视频不转码。');}
    }
    fetch(url(detail.thumbnail_url),{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail);return r.blob();}).then(blob=>{objectUrl=URL.createObjectURL(blob);if(valid)setDetailImage(objectUrl);}).catch(e=>{if(valid)setVideoError(e.message);});
    if(detail.stream_url){if(current)local(`/api/connections/${current.id}/media`,{url:detail.stream_url}).then(v=>{if(valid)setVideoUrl(v.url);}).catch(e=>{if(valid)setVideoError(e.message);});else setVideoUrl(detail.stream_url);}
    return()=>{valid=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};
  },[detail,url,token,current,local]);
  const select=(key:keyof Filters,value:any)=>{setOffset(0);setFilters(f=>{const old=f[key] as any[];return {...f,[key]:old.includes(value)?old.filter(v=>v!==value):[...old,value]};});};
  const chips=useMemo(()=>Object.entries(filters).filter(([k])=>!['mode','search'].includes(k)).flatMap(([k,values])=>(values as any[]).map(v=>({key:k,value:v,label:k==='missing'?`缺失：${missingNames[v]}`:k==='focals'?`${v} mm`:k==='focal_bins'?`${focalLabels[v]} mm 区间`:k==='roots'?roots.find(r=>r.id===v)?.label || v:k==='kinds'?(v==='photo'?'照片':'视频'):v}))),[filters,roots]);
  const libraryName=current?.name || (desktop?'本机图库':'NAS 共享图库');
  const showDetail=async(id:number)=>{const seq=revision.current;try{const data=await api<Asset>(`/api/assets/${id}`);if(seq===revision.current)setDetail(data);}catch(e:any){setError(e.message);}};
  const browse=async(p='')=>{setPath(p);try{setDirectories(await api('/api/browse?path='+encodeURIComponent(p)));}catch(e:any){setError(e.message);}};
  const login=()=>act(async()=>{if(setup){await api('/api/auth/setup',{password,setup_code:setupCode});setSetup(false);}const result=await api('/api/auth/login',{password,remember:!!current&&remember});if(result.warning)setError(result.warning);setPassword('');if(!current){sessionStorage.setItem('lens-session',result.token);setToken(result.token);}else{const i=await api('/api/info');setInfo(i);setCacheLimit(String(Math.round(i.cache.limit_bytes/1024**2)));setReady(true);setAuth(false);}},'已连接图库');

  // Store consent in each installation's database, including when using a remote NAS.
  const localNotice=desktop && localNoticeAccepted===false;
  if(connected && !auth && (localNotice || ((!desktop || localNoticeAccepted===true) && info?.usage_notice_accepted===false))) {
    return <UsageNotice key={localNotice?'desktop-local':connectionKey} onAccept={async()=>{
      const seq=revision.current;
      const result=await (localNotice?local:api)('/api/usage-notice/accept',{});
      if(result.usage_notice_accepted!==true)throw new Error('确认状态未保存');
      if(localNotice)setLocalNoticeAccepted(true);
      if(seq===revision.current && (!localNotice || !current))setInfo((value:any)=>({...value,usage_notice_accepted:true}));
    }}/>;
  }

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Aperture size={27}/></span><div>镜迹<small className="brand-credit">power by xiaokei</small><small>LENS ATLAS</small></div></div><div className="sidebar-label">工作空间</div><button className={`library-entry ${!current?'selected':''}`} onClick={()=>switchLibrary(null)}><HardDrive size={18}/><div>{desktop?'本机图库':'当前服务'}<small>{desktop?'此电脑 · 独立运行':'NAS · 浏览器访问'}</small></div>{!current&&<span className="live-dot"/>}</button>{desktop&&<><button className="connect-entry" onClick={()=>setDialog('nas')}><Network size={17}/>连接 NAS<span>＋</span></button>{connections.map(c=><div className="saved-connection" key={c.id}><button className={current?.id===c.id?'selected':''} onClick={()=>switchLibrary(c)}><span className="live-dot"/>{c.name}</button><button aria-label={`移除连接 ${c.name}`} onClick={()=>act(async()=>{await local(`/api/connections/${c.id}`,undefined,'DELETE');if(current?.id===c.id)switchLibrary(null);})}><X size={13}/></button></div>)}</>}<div className="sidebar-label spaced">图库分析</div><nav>{[{id:'overview',icon:LayoutDashboard,name:'统计概览'},{id:'wall',icon:ImageIcon,name:'素材浏览'},{id:'folders',icon:FolderOpen,name:'目录与扫描'},{id:'comparison',icon:Network,name:'图库比对'},{id:'settings',icon:Settings,name:'设置与维护'}].map(p=><button key={p.id} className={page===p.id?'selected':''} onClick={()=>setPage(p.id)}><p.icon size={18}/>{p.name}{p.id==='folders'&&scanning&&<LoaderCircle size={14} className="spin"/>}</button>)}</nav><div className="sidebar-bottom"><div className="read-only"><Check size={15}/>只读分析 · 原片始终保留</div><span>镜迹 {info?.version || ''} <span>LOCAL FIRST</span></span></div></aside>
    <main><header className="topbar"><div className="breadcrumb">工作空间<ChevronRight size={14}/><strong>{libraryName}</strong><span className="connection-badge">{current?'远端 NAS':desktop?'本机':'服务端'}</span></div><div className="topbar-right">{scanning&&<button className="scan-badge" onClick={()=>setPage('folders')}><LoaderCircle className="spin" size={14}/>扫描进行中</button>}<span className={`connection-dot ${ready?'online':''}`}/>{ready?'已连接':'未连接'}{ready&&(!desktop||current)&&<button className="icon-button" title="退出登录" onClick={()=>act(async()=>{await api('/api/auth/logout',{});setReady(false);setAuth(true);if(!current){sessionStorage.removeItem('lens-session');setToken('');}})}><LogOut size={16}/></button>}</div></header>
    <div className="content">{error&&<div className="banner error" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}{notice&&<div className="banner success" role="status"><Check size={18}/>{notice}</div>}
    {auth?<section className="auth card"><Aperture size={42}/><span className="eyebrow">YOUR LIBRARY, YOUR INSIGHTS</span><h1>{setup?'初始化管理员':'连接你的图库'}</h1><p>{libraryName}{current&&` · ${current.url}`}</p><form onSubmit={e=>{e.preventDefault();login();}}>{setup&&<label>初始化码<input required value={setupCode} onChange={e=>setSetupCode(e.target.value)} placeholder="服务端 data/setup-code.txt 中的内容" autoComplete="off"/></label>}<label>{setup?'设置管理员密码':'管理员密码'}<input required type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 10 个字符" autoComplete={setup?'new-password':'current-password'}/></label>{current&&<label className="remember-login"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>保持登录并自动连接</label>}<button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Network size={16}/>} {setup?'创建管理员并连接':'登录图库'}</button></form><p className="helper">登录状态仅在当前客户端生效；保持登录有效期为 30 天，退出登录会清除凭据。NAS 扫描不依赖客户端保持打开。</p></section>:!ready?<section className="empty card"><Network size={36}/><h2>正在连接 {libraryName}</h2><p>请确认服务已运行；远端服务不可用时可切回本机图库。</p><button onClick={()=>switchLibrary(current)}>重新连接</button></section>:<>
      <div className="page-heading"><div><span className="eyebrow">{page==='overview'?'LIBRARY INSIGHTS':page==='wall'?'EXPLORE YOUR ARCHIVE':page==='folders'?'LIBRARY SOURCES':'LIBRARY SETTINGS'}</span><h1>{page==='overview'?'让每一次拍摄，留下线索。':page==='wall'?'重新发现你的素材':page==='folders'?'目录与扫描':page==='comparison'?'图库比对':'设置与维护'}</h1><p>{page==='overview'?'从真实拍摄数据，发现你的器材偏好与创作轨迹。':page==='wall'?'组合筛选，随机重逢。每一张都来自当前图库。':page==='folders'?`这里操作的是「${libraryName}」所在的${current||!desktop?'服务端':'电脑'}目录。`:'缓存与索引独立存放，所有清理操作都不会修改原片。'}</p></div>{!['settings','comparison'].includes(page)&&<button className="primary" onClick={()=>{setDialog('root');setPath('');setLabel('');browse();}}><FolderPlus size={17}/>添加素材目录</button>}</div>
      {(page==='overview'||page==='wall')&&<><div className="filter-bar"><span><SlidersHorizontal size={17}/>筛选工作台</span><div className="segmented"><button className={filters.mode==='equivalent'?'active':''} onClick={()=>setFilters(f=>({...f,mode:'equivalent',focals:[],focal_bins:[]}))}>35mm 等效焦距</button><button className={filters.mode==='native'?'active':''} onClick={()=>setFilters(f=>({...f,mode:'native',focals:[],focal_bins:[]}))}>原生焦距</button></div><select aria-label="素材类型" value={filters.kinds[0]||''} onChange={e=>{setOffset(0);setFilters(f=>({...f,kinds:e.target.value?[e.target.value]:[]}));}}><option value="">全部媒体</option><option value="photo">仅照片</option><option value="video">仅视频</option></select><select aria-label="素材目录" value={filters.roots[0]||''} onChange={e=>{setOffset(0);setFilters(f=>({...f,roots:e.target.value?[Number(e.target.value)]:[]}));}}><option value="">全部目录</option>{roots.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select><button className="text-button" onClick={()=>{setFilters(blank(filters.mode));setOffset(0);}}>重置</button></div>{(chips.length>0||filters.search)&&<div className="filter-chips"><small>条件间取交集 · 同类多选取并集</small>{chips.map(c=><button key={c.key+String(c.value)} onClick={()=>select(c.key as keyof Filters,c.value)}>{c.label}<X size={12}/></button>)}{filters.search&&<button onClick={()=>setFilters(f=>({...f,search:''}))}>名称：{filters.search}<X size={12}/></button>}</div>}</>}
      {page==='overview'&&stats&&<><div className="metrics"><Metric icon={ImageIcon} label="当前筛选素材" value={num(stats.summary.count)} hint={`${num(stats.summary.photos)} 张照片 · ${num(stats.summary.videos)} 段视频`}/><Metric icon={Database} label="素材占用空间" value={bytes(stats.summary.bytes)} hint="RAW 与 JPG 分别计数，不自动合并"/><Metric icon={Camera} label="使用相机" value={num(stats.cameras.length)} hint={`${num(stats.lenses.length)} 支镜头留下拍摄记录`}/><Metric icon={Aperture} label="有拍摄时间" value={num(stats.summary.count-stats.missing.time.count)} hint="只使用元数据拍摄时间，保留来源"/></div><div className="section-heading"><div><h2>拍摄画像</h2><p>点击任意图表联动筛选全部图表、统计与素材；再次点击取消，重置恢复全部。</p></div><span className="soft-label">真实索引 · {filters.mode==='equivalent'?'35mm 等效':'原生'}焦距</span></div><div className="charts-grid"><Chart title="相机" subtitle="哪些机身陪你记录最多" rows={stats.cameras} selected={filters.cameras} onSelect={v=>select('cameras',v)}/><Chart title="镜头" subtitle="从器材选择，看见拍摄偏好" rows={stats.lenses} selected={filters.lenses} onSelect={v=>select('lenses',v)}/><FocalChart key={connectionKey+filters.mode} data={focalData} mode={filters.mode} bins={filters.focal_bins} values={filters.focals} onBin={v=>{setOffset(0);setFilters(f=>({...f,focals:[],focal_bins:f.focal_bins.includes(v)?[]:[v]}));}} onValue={v=>{setOffset(0);setFilters(f=>({...f,focals:f.focals.includes(v)?[]:[v],focal_bins:[]}));}}/><Chart title="拍摄时间" subtitle="按元数据记录的本地年月分组" rows={stats.months} selected={filters.months} onSelect={v=>select('months',v)} type="line"/></div><section className="card missing-card"><div className="card-title"><div><h3><AlertCircle size={17}/>缺失信息</h3><p>各分组可以重叠；「缺少任一字段」按文件去重，仅统计数量与大小。</p></div></div><div className="missing-grid">{['any','camera','lens','focal','time'].map(k=><button key={k} className={filters.missing.includes(k)?'active':''} onClick={()=>select('missing',k)}><span>{k==='any'?missingNames[k]:`${missingNames[k]}缺失`}</span><strong>{num(stats.missing[k].count)}<small>个文件</small></strong><span>{bytes(stats.missing[k].bytes)}</span></button>)}</div></section></>}
      {(page==='overview'||page==='wall')&&<section className="wall-section"><div className="section-heading"><div><h2>{sampling?'随机重逢':'素材浏览'}<span className="count-pill">{num(total)}</span></h2><p>{sampling?'从完整的当前筛选结果中随机抽取最多 24 个文件。':'按索引顺序分页，每页 24 个文件。'}预览失败不会影响统计。</p></div><div className="wall-tools"><label className="search"><Search size={15}/><input aria-label="搜索文件名" placeholder="搜索文件名或相对路径" value={filters.search} onChange={e=>{setOffset(0);setFilters(f=>({...f,search:e.target.value}));}}/></label><button onClick={()=>{setSampling(!sampling);setOffset(0);}}>{sampling?'顺序浏览':'随机抽样'}</button><button className="primary-outline" disabled={loading} onClick={()=>setSample(n=>n+1)}>{loading?<LoaderCircle size={16} className="spin"/>:<Shuffle size={16}/>}换一批</button></div></div>{items.length?<div className={`photo-grid ${loading?'loading':''}`}>{items.map(item=><Photo key={connectionKey+item.id} item={item} token={token} url={url} onClick={()=>showDetail(item.id)}/>)}</div>:<div className="empty card"><ImageIcon size={40}/><h2>{roots.length?'当前条件下还没有素材':'从第一个素材目录开始'}</h2><p>{roots.length?'完成扫描后即可查看；也可以清除筛选条件。':'添加你选择的目录，镜迹将只读扫描，并在这里呈现真实照片和统计。'}</p>{!roots.length&&<button className="primary" onClick={()=>{setDialog('root');browse();}}>添加素材目录</button>}</div>}{!sampling&&total>24&&<div className="pagination"><button disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-24))}>上一页</button><span>{Math.floor(offset/24)+1} / {Math.ceil(total/24)}</span><button disabled={offset+24>=total} onClick={()=>setOffset(v=>v+24)}>下一页</button></div>}<div className="wall-footer"><span>只读索引 · 无原片上传 · 缩略图按需加载</span><span>当前图库：{libraryName}</span></div></section>}
      {page==='folders'&&stats&&<section className="card inventory-card"><div className="card-title"><div><h3>全部索引的文件分类</h3><p>照片和视频参与摄影统计；非媒体与未知类型单独计数，不混入图表。</p></div></div><div className="inventory-grid">{stats.inventory.map(row=><div key={row.kind}><span>{{photo:'照片',video:'视频',nonmedia:'非媒体文件',unknown:'未知类型'}[row.kind]}</span><strong>{num(row.count)}</strong><small>{bytes(row.bytes)}</small></div>)}</div></section>}
      {page==='folders'&&<><section className="card"><div className="card-title"><div><h3>素材目录</h3><p>重叠目录会被拒绝；符号链接与目录联接不跟随。首次扫描分为枚举、元数据和预览三阶段。</p></div></div>{!roots.length?<div className="empty"><FolderOpen size={32}/><p>尚未添加素材目录</p></div>:roots.map(root=><div className="root-row" key={root.id}><div className="folder-icon"><FolderOpen size={24}/></div><div className="root-name"><strong>{root.label}<span className={`status ${root.status}`}>{statusNames[root.status]}</span></strong><code>{root.path}</code><small>{num(root.file_count)} 个已索引文件 {root.error&&` · ${root.error}`}</small></div><button disabled={busy} onClick={()=>act(()=>api(`/api/roots/${root.id}/scan`,{}),'扫描已加入队列')}><RefreshCw size={15}/>增量扫描</button><button disabled={busy} onClick={()=>act(()=>api(`/api/roots/${root.id}/scan?force=true`,{}),'完整重读已加入队列')}>重新读取</button><button title="移除目录索引" aria-label={`移除 ${root.label}`} onClick={()=>{if(confirm(`从图库移除「${root.label}」的索引？原片不会被删除。`))act(()=>api(`/api/roots/${root.id}`,undefined,'DELETE'),'已移除索引，原片未修改');}}><Trash2 size={15}/></button></div>)}</section><section className="card jobs-card"><div className="card-title"><div><h3>扫描任务</h3><p>暂停和取消将在正在处理的有限批次结束后生效。任务和已完成索引持续保存在服务端。</p></div></div>{!jobs.length?<div className="empty"><p>暂无扫描任务</p></div>:jobs.map(job=><div className="job-row" key={job.id}><div className="job-heading"><strong>{job.root_label}</strong><span className={`status ${job.status}`}>{statusNames[job.status]}</span><small>{statusNames[job.phase]}</small><span className="job-actions">{['queued','running'].includes(job.status)&&<button aria-label="暂停任务" onClick={()=>act(()=>api(`/api/jobs/${job.id}/pause`,{}))}><Pause size={14}/></button>}{['paused','failed','cancelled'].includes(job.status)&&<button onClick={()=>act(()=>api(`/api/jobs/${job.id}/resume`,{}))}><Play size={14}/>恢复</button>}{['queued','running','paused'].includes(job.status)&&<button aria-label="取消任务" onClick={()=>act(()=>api(`/api/jobs/${job.id}/cancel`,{}))}><Square size={14}/></button>}</span></div><progress max={job.total||1} value={job.status==='completed'?(job.total||1):job.processed}/><p>已枚举 {num(job.enumerated)} 个文件 · 本阶段 {num(job.processed)} / {num(job.total)} · 问题/跳过 {num(job.errors)}{job.message&&` · ${job.message}`}</p></div>)}</section><div className="info-note"><AlertCircle size={17}/>无权限的个别子目录会被跳过并显示警告，其他文件继续扫描。未在本次扫描找到的历史文件仍保留索引，防止断线造成误删；详情中单独显示可用性。增量扫描按路径、大小与修改时间检测变化，不默认计算原片哈希。</div></>}
      {page==='comparison'&&<Comparison api={local} download={download} desktop={desktop}/>}
      {page==='settings'&&info&&<div className="settings-grid"><section className="card"><div className="card-title"><div><h3>预览缓存</h3><p>当前设置应用于 {libraryName}</p></div></div><p className="cache-value">{bytes(info.cache.bytes)} <small>/ {bytes(info.cache.limit_bytes)}</small></p><label>容量上限（MB）<input type="text" inputMode="numeric" value={cacheLimit} onChange={e=>{cacheDraftRevision.current++;setCacheLimit(e.target.value);}} placeholder="16–1048576"/></label><div className="button-row"><button className="primary" disabled={busy} onClick={()=>act(async()=>{const text=cacheLimit.trim();if(!/^\d+$/.test(text)||!Number.isSafeInteger(Number(text))||Number(text)<16||Number(text)>1048576)throw new Error('请输入 16–1048576 之间的整数容量（MB）；空白不会保存');const value=Number(text);const cache=await api('/api/cache',{limit_bytes:value*1024**2},'PUT');setCacheLimit(String(value));setInfo({...info,cache});},'缓存上限已保存')}>保存上限</button><button disabled={busy} onClick={()=>act(async()=>{const cache=await api('/api/cache',undefined,'DELETE');setInfo({...info,cache});},'缩略图缓存已清理；再次查看时按需重建')}>清理缓存</button></div><p className="helper">缓存按最近使用时间淘汰。清理不会影响原片和元数据统计。</p></section><section className="card"><div className="card-title"><div><h3>服务与工具</h3><p>图库 ID：{info.library_id}</p></div></div>{Object.entries(info.tools).map(([key,value])=><div className="setting-row" key={key}><span>{key}</span><span className={value?'tool-ok':'tool-missing'}>{value?'已发现':'未安装 / 部分能力受限'}</span></div>)}<div className="setting-row"><span>服务版本</span><span>{info.version} · API {info.api_version}</span></div><div className="setting-row"><span>文件处理限制</span><span>{info.scan_workers} 并发 / {info.single_file_timeout} 秒超时</span></div><button onClick={()=>act(()=>api('/api/backup',{}),'一致性备份已写入服务端应用数据目录：backup.sqlite3（含管理员配置，请保密）')}><Download size={16}/>创建数据库备份</button></section><section className="card format-note"><h3>格式能力说明</h3><p>元数据读取、缩略图生成和预览播放分别记录。RAW 优先提取内嵌 JPEG，没有可用内嵌图像时仅尝试现有图片解码器；不承诺所有相机格式均可预览。</p><p>视频按需生成封面，不批量转码。实际播放取决于浏览器和视频编码。等效焦距仅采用明确元数据值，缺少时不使用原生焦距代替。</p><p>拍摄时间不使用文件修改时间替代；可能来自相机 EXIF 或视频容器创建时间，详情保留具体来源。非媒体和未知扩展名不计入摄影统计。</p></section></div>}
    </>}</div></main>
    {dialog&&<div className="modal-backdrop" onClick={()=>setDialog(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={dialog==='root'?'添加素材目录':'连接 NAS'} onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{dialog==='root'?'添加素材目录':'连接 NAS'}</h2><button className="icon-button" aria-label="关闭对话框" onClick={()=>setDialog(null)}><X/></button></div>{error&&<div className="banner error" role="alert"><AlertCircle size={16}/><span>{error}</span></div>}{dialog==='root'?<form onSubmit={e=>{e.preventDefault();act(async()=>{const root=await api<Root>('/api/roots',{path,label});await api(`/api/roots/${root.id}/scan`,{});setDialog(null);setPage('folders');},'目录已添加并开始扫描');}}><div className="info-note"><HardDrive size={17}/>选择的是 {libraryName} 的{current||!desktop?'服务端路径；无需在电脑挂载 SMB':'本机或已授权 SMB 路径'}。</div><p className="usage-notice-reminder">请先用测试文件夹验证无异常，再添加正式数据；使用前请独立备份重要资料。因使用本软件导致的资料丢失、损坏或其他损失，开发者概不负责。</p><label>目录路径<input required value={path} onChange={e=>setPath(e.target.value)} placeholder={current||!desktop?'/media/photos':'D:\\照片 或 \\\\NAS\\共享\\照片'}/></label><div className="button-row"><button type="button" onClick={()=>browse(path)}>浏览此路径</button><button type="button" onClick={()=>browse('')}>可用根目录</button></div><div className="directory-list">{directories?.parent&&<button type="button" onClick={()=>browse(directories.parent)}><ArrowLeft size={15}/>上一级</button>}{directories?.directories.map((d:any)=><button type="button" key={d.path} onClick={()=>browse(d.path)}><FolderOpen size={16}/>{d.name}<ChevronRight size={14}/></button>)}{directories?.directories.length===0&&<p>没有子文件夹；可以选择当前目录。</p>}</div><label>显示名称（可选）<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="例如：旅行与日常"/></label><button className="primary" disabled={busy||!path}><FolderPlus size={17}/>添加并扫描</button></form>:<form onSubmit={e=>{e.preventDefault();act(async()=>{const c=await local<Connection>('/api/connections',{name:nasName,url:nasUrl});setConnections(v=>[...v,c]);setDialog(null);setNasName('');setNasUrl('');switchLibrary(c);});}}><p>扫描由 NAS 执行，关闭此窗口不会停止 NAS 任务。每个图库的统计独立显示。</p><label>连接名称<input required value={nasName} onChange={e=>setNasName(e.target.value)} placeholder="例如：家中 NAS"/></label><label>服务地址<input required type="url" value={nasUrl} onChange={e=>setNasUrl(e.target.value)} placeholder="http://192.168.1.10:52032"/></label><p className="helper">默认用于可信局域网；可保持登录，安全保存会话，不保存明文密码。HTTPS 证书始终校验。</p><button className="primary" disabled={busy}><Network size={17}/>保存并连接</button></form>}</section></div>}
    {detail&&<div className="modal-backdrop detail-backdrop" onClick={()=>setDetail(null)}><section className="detail-modal" role="dialog" aria-modal="true" aria-label="素材详情" onClick={e=>e.stopPropagation()}><div className="detail-preview">{detail.kind==='video'&&videoUrl&&!inlineUnsupported?<video controls preload="metadata" poster={detailImage} src={videoUrl} onLoadedData={event=>{if(event.currentTarget.videoWidth===0){setInlineUnsupported(true);setVideoError('当前内嵌播放器只读到音轨，不能显示视频画面。请使用原生播放器。');}}} onError={()=>{setInlineUnsupported(true);setVideoError('当前内嵌播放器无法解码或原片不可用；未自动转码。');}}/>:detailImage?<img src={detailImage} alt={detail.relpath}/>:<div className="photo-unavailable"><ImageIcon size={48}/><p>此素材暂无可用预览</p></div>}{videoError&&<p className="preview-message">{videoError}</p>}{detail.kind==='video'&&nativePlayback&&<button className="primary native-play-button" disabled={!videoUrl} onClick={()=>{local('/api/player/open',{url:videoUrl,title:detail.relpath.split('/').pop()}).catch(e=>setVideoError(e.message));}}><Play size={17}/>在桌面播放器中打开</button>}</div><div className="detail-info"><div className="modal-header"><span className="eyebrow">ASSET DETAILS</span><button className="icon-button" aria-label="关闭素材详情" onClick={()=>setDetail(null)}><X/></button></div><h2>{detail.relpath.split('/').pop()}</h2><p className="filepath">{detail.root_label} / {detail.relpath}</p><div className="detail-tags"><span>{detail.ext.toUpperCase()}</span><span>{bytes(detail.size)}</span><span>{detail.width&&detail.height?`${detail.width} × ${detail.height}`:'尺寸未知'}</span></div><dl>{[['相机',detail.camera],['镜头',detail.lens],[filters.mode==='equivalent'?'35mm 等效焦距':'原生焦距',(filters.mode==='equivalent'?detail.focal_equiv:detail.focal_native)?`${filters.mode==='equivalent'?detail.focal_equiv:detail.focal_native} mm`:null],['等效焦距来源',detail.focal_source],['原生焦距',detail.focal_native?`${detail.focal_native} mm`:null],['拍摄时间',detail.taken_at],['时间来源',detail.time_source],['光圈',detail.aperture?`f/${detail.aperture}`:null],['曝光时间',detail.shutter?`${detail.shutter} s`:null],['ISO',detail.iso],['视频编码',detail.codec],['时长',detail.duration?`${detail.duration.toFixed(2)} 秒`:null]].map(([k,v])=><div key={k}><dt>{k}</dt><dd className={!v?'muted':''}>{v || '缺失 / 未记录'}</dd></div>)}</dl><div className="detail-status"><p>元数据：{statusNames[detail.metadata_status]}</p><p>预览：{statusNames[detail.preview_status]}</p><p>文件：{statusNames[detail.availability||'unknown']}</p>{detail.kind==='video'&&<p>播放：{statusNames[detail.playback_status]}</p>}{(detail.metadata_error||detail.preview_error)&&<p className="helper">{detail.metadata_error}<br/>{detail.preview_error}</p>}</div><details><summary>查看原始元数据及字段来源</summary><pre>{JSON.stringify(detail.metadata,null,2)}</pre></details></div></section></div>}
  </div>;
}
