import { useEffect, useRef, useState } from 'react';
import { Aperture, Camera, ChevronDown, Database, FolderOpen, HardDrive, Image as ImageIcon, LayoutDashboard, LoaderCircle, Network, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Video, X } from 'lucide-react';
import { Chart, Metric } from './LibraryWidgets';
import FocalChart, { focalDistribution } from './FocalChart';
import { native } from './androidBridge';
import RemoteScanPanel from './RemoteScanPanel';

type Filters={mode:'equivalent'|'native';cameras:string[];lenses:string[];months:string[];focals:number[];focal_bins:number[];kinds:string[];missing:string[];search:string};
type Group={value:string|number;count:number;bytes:number};
type Stats={summary:{count:number;bytes:number;photos:number;videos:number};cameras:Group[];lenses:Group[];months:Group[];focals:Group[];missing:Record<string,{count:number;bytes:number}>};
type Asset={id:string|number;relpath:string;kind:string;size:number;ext:string;camera:string|null;lens:string|null;taken_at:string|null;focal_native:number|null;focal_equiv:number|null;width:number|null;height:number|null;iso:string|null;aperture:string|null;shutter:string|null;duration:number|null;metadata_error:string|null;thumbnail_url?:string;root_label?:string};
type Status={authorized:boolean;scope:string;scanning:boolean;message:string;lastScan:string|null;revision:number};
type Connection={slot:number;name:string;url:string;remembered?:boolean;kind?:'nas'|'computer';warning?:string|null};
type Source='local'|'nas';
const blank=(mode:Filters['mode']='equivalent'):Filters=>({mode,cameras:[],lenses:[],months:[],focals:[],focal_bins:[],kinds:[],missing:[],search:''});
const num=(n:number=0)=>n.toLocaleString('zh-CN');
const bytes=(n:number=0)=>n>=1024**4?(n/1024**4).toFixed(2)+' TB':n>=1024**3?(n/1024**3).toFixed(2)+' GB':n>=1024**2?(n/1024**2).toFixed(1)+' MB':(n/1024).toFixed(1)+' KB';
const missingLabels:Record<string,string>={camera:'相机',lens:'镜头',focal:'焦距',time:'拍摄时间',any:'任一字段'};

function Preview({item,source,detail=false}:{item:Asset;source:Source;detail?:boolean}){
  const [src,setSrc]=useState(''),[error,setError]=useState(false);
  const element=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    let valid=true,started=false;
    setSrc('');setError(false);
    const load=()=>{if(started)return;started=true;native<string>('thumbnail',{source,id:item.id,path:item.thumbnail_url}).then(value=>{if(valid)setSrc(value);}).catch(()=>{if(valid)setError(true);});};
    const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){load();observer.disconnect();}},{rootMargin:'200px'});
    if(element.current)observer.observe(element.current);else load();
    return()=>{valid=false;observer.disconnect();};
  },[source,item.id,item.thumbnail_url]);
  return <div ref={element} className={detail?'mobile-detail-image':'photo-image'}>{src?<img src={src} alt={item.relpath} loading="lazy"/>:error?<div className="photo-unavailable"><ImageIcon size={28}/><small>预览暂不可用</small></div>:<LoaderCircle className="spin"/>}{!detail&&<span className="format">{item.kind==='video'&&<Video size={11}/>} {item.ext.toUpperCase()}</span>}</div>;
}

export default function MobileApp(){
  const [source,setSource]=useState<Source>('local'),[connection,setConnection]=useState<Connection|null>(null),[connections,setConnections]=useState<Connection[]>([]);
  const [page,setPage]=useState('overview'),[picker,setPicker]=useState(false),[login,setLogin]=useState<Connection|null>(null);
  const [name,setName]=useState(''),[address,setAddress]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(true);
  const [status,setStatus]=useState<Status|null>(null),[stats,setStats]=useState<Stats|null>(null),[filters,setFilters]=useState<Filters>(blank());
  const [items,setItems]=useState<Asset[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0),[sample,setSample]=useState(0),[random,setRandom]=useState(false);
  const [detail,setDetail]=useState<Asset|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
  const [albums,setAlbums]=useState<{key:string;label:string;count:number}[]>([]),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState('');
  const sourceRef=useRef(source);sourceRef.current=source;
  const revision=useRef(0),lastScanRevision=useRef<number|null>(null),galleryTop=useRef<HTMLElement|null>(null);
  const libraryName=source==='nas'?connection?.name||'远程图库':'手机图库';
  const act=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const clear=()=>{setFilters(blank(filters.mode));setSearch('');setOffset(0);};
  const changeSource=(next:Source,c:Connection|null=null)=>{revision.current++;if(next==='local')native('selectLocal').catch(e=>setError(e.message));setSource(next);setConnection(c);setPage('overview');setFilters(blank());setSearch('');setStats(null);setItems([]);setDetail(null);setError('');setNotice('');setOffset(0);setPicker(false);};
  useEffect(()=>{
    let valid=true;const seq=revision.current;
    native<{connections:Connection[];active:Connection|null;login:Connection|null;message?:string}>('bootstrap').then(result=>{
      if(!valid||seq!==revision.current)return;setConnections(result.connections);
      if(result.active){changeSource('nas',result.active);setNotice(result.message||'已恢复上次登录与图库');}
      else if(result.login){showLogin(result.login);if(result.message)setError(result.message);}
    }).catch(e=>{if(valid)setError(e.message);});
    return()=>{valid=false;};
  },[]);
  useEffect(()=>{native<Connection[]>('connections').then(setConnections).catch(e=>setError(e.message));},[refresh]);
  useEffect(()=>{
    let valid=true;
    const poll=()=>native<Status>('status').then(value=>{if(!valid)return;setStatus(value);if(lastScanRevision.current!==null&&lastScanRevision.current!==value.revision){setRefresh(n=>n+1);if(sourceRef.current==='local'){setDetail(null);setItems([]);}}lastScanRevision.current=value.revision;}).catch(e=>{if(valid)setError(e.message);});
    poll();const timer=setInterval(poll,1500);return()=>{valid=false;clearInterval(timer);};
  },[]);
  const localReady=!!status?.authorized&&!status.scanning;
  const ready=source==='nas'?!!connection:localReady;
  useEffect(()=>{
    if(!ready){setStats(null);return;}
    let valid=true;setLoading(true);setError('');
    native<Stats>('stats',{source,filters}).then(value=>{if(valid)setStats(value);}).catch(e=>{if(valid){setError(e.message);setStats(null);}}).finally(()=>{if(valid)setLoading(false);});
    return()=>{valid=false;};
  },[source,connection,filters,ready,refresh]);
  useEffect(()=>{
    if(!ready||page!=='gallery')return;
    let valid=true;setLoading(true);setItems([]);
    native<{items:Asset[];total:number}>('query',{source,filters,offset,limit:24,random}).then(value=>{if(valid){setItems(value.items);setTotal(value.total);}}).catch(e=>{if(valid)setError(e.message);}).finally(()=>{if(valid)setLoading(false);});
    return()=>{valid=false;};
  },[source,connection,filters,ready,refresh,page,offset,sample,random]);
  useEffect(()=>{if(page!=='scan'||source!=='local'||!status?.authorized||status.scanning)return;let valid=true;native<typeof albums>('albums').then(value=>{if(valid){setAlbums(value);setSelected(old=>old.filter(k=>value.some(a=>a.key===k)));}}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};},[page,source,status?.authorized,status?.scanning,refresh]);
  useEffect(()=>{window.__lensBack=()=>{if(detail){setDetail(null);return true;}if(login){setLogin(null);return true;}if(picker){setPicker(false);return true;}if(page!=='overview'){setPage('overview');return true;}return false;};return()=>{delete window.__lensBack;};},[detail,login,picker,page]);
  const select=(key:'cameras'|'lenses'|'months'|'kinds'|'missing',value:string)=>{setOffset(0);setFilters(f=>({...f,[key]:f[key].includes(value)?f[key].filter(v=>v!==value):[...f[key],value]}));};
  const focal=(key:'focals'|'focal_bins',value:number)=>{setOffset(0);setFilters(f=>({...f,focals:key==='focals'&&!f.focals.includes(value)?[value]:[],focal_bins:key==='focal_bins'&&!f.focal_bins.includes(value)?[value]:[]}));};
  const openDetail=(item:Asset)=>{const seq=revision.current;act(async()=>{const value=await native<Asset>('detail',{source,id:item.id});if(seq===revision.current)setDetail(value);});};
  const chipEntries=Object.entries(filters).filter(([k])=>!['mode','search'].includes(k)).flatMap(([k,values])=>(values as (string|number)[]).map(v=>({key:k,value:v,label:k==='missing'?`缺失 ${missingLabels[v]}`:k==='kinds'?(v==='photo'?'照片':'视频'):k==='focals'?`${v} mm`:k==='focal_bins'?`焦距区间 ${Number(v)+1}`:String(v)})));
  const startScan=(chosen:string[]|null)=>act(async()=>{await native('scan',{selected:chosen});setNotice('已开始只读扫描，索引与缓存保存在应用自己的目录');setRefresh(n=>n+1);});
  const showLogin=(c:Connection)=>{setLogin(c);setName(c.name);setAddress(c.url);setPassword('');setRemember(true);setError('');setPicker(false);};
  const openLogin=(c:Connection)=>{
    if(!c.remembered){showLogin(c);return;}
    const seq=++revision.current;setPicker(false);
    act(async()=>{const result=await native<{active:Connection|null;login:Connection|null;message?:string}>('restore',{slot:c.slot});if(seq!==revision.current)return;if(result.active){changeSource('nas',result.active);setNotice(result.message||'已恢复保存的登录');}else{showLogin(result.login||c);if(result.message)setError(result.message);}});
  };
  const connect=()=>{const target=login;if(!target)return;const seq=++revision.current;const secret=password;setPassword('');act(async()=>{const c=await native<Connection>('connect',{slot:target.slot,name,url:address,password:secret,remember});if(seq!==revision.current)return;changeSource('nas',c);setLogin(null);setNotice(c.warning||(c.remembered?'已连接 · 下次打开将自动恢复登录':'已连接 · 本次不保存登录')); setRefresh(n=>n+1);});};
  const go=(next:string)=>{setPage(next);setError('');window.scrollTo({top:0});};
  return <div className="mobile-app">
    <header className="mobile-header"><div className="brand"><span className="brand-icon"><Aperture size={25}/></span><div>镜迹<small>LENS ATLAS</small></div></div><button className="mobile-source" onClick={()=>setPicker(true)}>{source==='nas'?<Network size={15}/>:<HardDrive size={15}/>}<span>{libraryName}</span><ChevronDown size={14}/></button></header>
    <main className="mobile-content"><div className="mobile-context"><span className="live-dot"/>{source==='nas'?(stats?(connection?.kind==='computer'?'电脑已连接':'NAS 已连接'):loading?'正在读取服务端':'连接需检查'):status?.scanning?'正在扫描':status?.authorized?'本地图库':'等待授权'}<span><ShieldCheck size={12}/>原始素材只读</span></div>
      {error&&<div className="banner error" role="alert">{error}<button aria-label="关闭错误" className="icon-button" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="banner">{notice}<button className="icon-button" aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
      {(page==='overview'||page==='gallery')&&<><div className="mobile-page-heading"><div><span className="eyebrow">{page==='overview'?'LIBRARY OVERVIEW':'PHOTO GALLERY'}</span><h1>{page==='overview'?'图库信息':'素材浏览'}</h1><p>{source==='nas'?connection?.url:status?.scope||'授权后，扫描你的照片与视频'}</p></div><button className="icon-button" aria-label="刷新数据" disabled={!ready||loading} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={18} className={loading?'spin':''}/></button></div>
        {source==='local'&&!status?.authorized&&<section className="card mobile-empty"><Camera size={38}/><h2>从你的相册开始</h2><p>扫描照片与视频，发现相机、镜头与拍摄习惯。照片保留在原处。</p><button className="primary" onClick={()=>act(()=>native('authorize'))}>授权读取相册</button><button onClick={()=>setPicker(true)}><Network size={16}/>连接 NAS 图库</button></section>}
        {source==='local'&&status?.scanning&&<section className="card mobile-empty"><LoaderCircle className="spin"/><h2>正在读取相册</h2><p>{status.message}</p><button onClick={()=>go('scan')}>查看扫描进度</button></section>}
        {ready&&<><div className="mobile-filterbar"><div className="segmented"><button className={filters.mode==='equivalent'?'active':''} onClick={()=>{setFilters(f=>({...f,mode:'equivalent',focals:[],focal_bins:[]}));setOffset(0);}}>35mm 等效</button><button className={filters.mode==='native'?'active':''} onClick={()=>{setFilters(f=>({...f,mode:'native',focals:[],focal_bins:[]}));setOffset(0);}}>原生焦距</button></div><button onClick={clear}><SlidersHorizontal size={14}/>重置</button></div>
          <div className="mobile-chips">{chipEntries.map(c=><button key={c.key+String(c.value)} onClick={()=>{setOffset(0);setFilters(f=>({...f,[c.key]:(f[c.key as keyof Filters] as (string|number)[]).filter(v=>v!==c.value)}));}}>{c.label}<X size={11}/></button>)}{filters.search&&<button onClick={()=>{setFilters(f=>({...f,search:''}));setSearch('');setOffset(0);}}>搜索：{filters.search}<X size={11}/></button>}</div>
          {page==='overview'&&stats&&<><div className="metrics mobile-metrics"><Metric icon={ImageIcon} label="照片与视频" value={num(stats.summary.count)} hint={`照片 ${num(stats.summary.photos)} · 视频 ${num(stats.summary.videos)}`}/><Metric icon={Database} label="素材总容量" value={bytes(stats.summary.bytes)} hint="原始素材大小，不含应用缓存"/><Metric icon={Camera} label="相机型号" value={num(stats.cameras.length)} hint="当前筛选中的已记录型号"/><Metric icon={Aperture} label="镜头型号" value={num(stats.lenses.length)} hint="未记录的字段保持缺失"/></div><div className="mobile-charts"><Chart title="相机" subtitle="点击分类联动筛选，再次点击取消" rows={stats.cameras} selected={filters.cameras} onSelect={v=>select('cameras',String(v))}/><Chart title="镜头" subtitle="当前筛选中的镜头分布" rows={stats.lenses} selected={filters.lenses} onSelect={v=>select('lenses',String(v))}/><FocalChart data={focalDistribution(stats.focals.map(r=>({...r,value:Number(r.value)})))} mode={filters.mode} bins={filters.focal_bins} values={filters.focals} onBin={v=>focal('focal_bins',v)} onValue={v=>focal('focals',v)}/><Chart title="拍摄时间" subtitle="按拍摄月份统计，缺失时间不使用修改时间代替" type="line" rows={stats.months} selected={filters.months} onSelect={v=>select('months',String(v))}/></div><section className="card mobile-missing"><div className="card-title"><div><h3>元数据完整性</h3><p>点击缺失项查看对应素材</p></div></div><div className="mobile-missing-grid">{Object.entries(missingLabels).map(([key,label])=><button key={key} className={filters.missing.includes(key)?'active':''} onClick={()=>select('missing',key)}><span>缺少{label}</span><strong>{num(stats.missing[key]?.count||0)}</strong></button>)}</div></section><button className="primary mobile-browse" onClick={()=>go('gallery')}><ImageIcon size={17}/>浏览当前筛选的素材</button>{source==='local'&&stats.summary.count===0&&<p className="helper">尚未建立索引，或当前没有符合筛选的素材。到“扫描”选择相册开始扫描。</p>}</>}
          {page==='gallery'&&<section ref={galleryTop} className="mobile-gallery"><form className="mobile-search" onSubmit={e=>{e.preventDefault();setFilters(f=>({...f,search}));setOffset(0);}}><Search size={16}/><input aria-label="搜索素材文件名" placeholder="搜索素材文件名" value={search} onChange={e=>setSearch(e.target.value)}/><button>搜索</button></form><div className="mobile-wall-tools"><span>{num(total)} 个素材</span><button className={filters.kinds.includes('photo')?'active':''} onClick={()=>select('kinds','photo')}>照片</button><button className={filters.kinds.includes('video')?'active':''} onClick={()=>select('kinds','video')}>视频</button><button onClick={()=>{setRandom(!random);setOffset(0);}}> {random?'随机浏览':'顺序浏览'}</button></div>{loading?<div className="mobile-loading"><LoaderCircle className="spin"/>正在读取素材…</div>:<div className="photo-grid">{items.map(item=><button className="photo" key={item.id} onClick={()=>openDetail(item)}><Preview item={item} source={source}/><div className="photo-caption"><strong>{item.relpath.split('/').pop()}</strong><span>{item.camera||'相机信息缺失'}</span></div></button>)}</div>}{!loading&&!items.length&&<div className="card mobile-empty"><ImageIcon/><p>当前范围没有素材</p></div>}<div className="mobile-pagination">{random?<button disabled={loading} onClick={()=>setSample(n=>n+1)}>换一批</button>:<><button disabled={!offset||loading} onClick={()=>{setOffset(n=>Math.max(0,n-24));galleryTop.current?.scrollIntoView();}}>上一页</button><span>{Math.floor(offset/24)+1} / {Math.max(1,Math.ceil(total/24))}</span><button disabled={offset+24>=total||loading} onClick={()=>{setOffset(n=>n+24);galleryTop.current?.scrollIntoView();}}>下一页</button></>}</div></section>}
        </>}
      </>}
      {page==='scan'&&<><div className="mobile-page-heading"><div><span className="eyebrow">READ-ONLY SCANNER</span><h1>相册与扫描</h1><p>{source==='nas'?'扫描服务端已有目录，原始素材只读':status?.scope||'读取系统授权的照片与视频'}</p></div><FolderOpen/></div>{source==='nas'&&connection?<RemoteScanPanel key={connection.url} url={connection.url} onRefresh={()=>setRefresh(n=>n+1)}/>:<><section className="card mobile-scan-status"><div className="card-title"><div><h3>{status?.scanning?'正在扫描':'只读扫描'}</h3><p>{status?.message||'尚未扫描'}</p></div>{status?.scanning?<LoaderCircle className="spin"/>:<ShieldCheck/>}</div><p className="helper">不上传、不移动、不重命名，不修改照片、视频或 EXIF。索引只保存在镜迹应用目录。</p><div className="button-row"><button disabled={busy||status?.scanning} onClick={()=>act(()=>native('authorize'))}>授权 / 调整读取范围</button>{status?.scanning?<button onClick={()=>act(()=>native('cancel'))}>取消扫描</button>:<button className="primary" disabled={!status?.authorized||busy} onClick={()=>startScan(null)}>扫描全部已授权相册</button>}</div>{status?.lastScan&&<p className="helper">上次完成：{status.lastScan}</p>}</section><section className="card mobile-albums"><div className="card-title"><div><h3>指定相册</h3><p>共 {albums.length} 个可访问相册 · 已选 {selected.length} 个</p></div><button disabled={!albums.length||status?.scanning} onClick={()=>setSelected(selected.length===albums.length?[]:albums.map(a=>a.key))}>{selected.length===albums.length?'取消全选':'全选'}</button></div>{albums.map(album=><label className="mobile-album" key={album.key}><input type="checkbox" disabled={status?.scanning} checked={selected.includes(album.key)} onChange={()=>setSelected(old=>old.includes(album.key)?old.filter(k=>k!==album.key):[...old,album.key])}/><FolderOpen size={20}/><span>{album.label}<small>{num(album.count)} 个素材</small></span></label>)}{!albums.length&&<p className="helper">授权后显示系统可访问的相册。</p>}<button className="primary" disabled={!selected.length||status?.scanning||busy} onClick={()=>startScan(selected)}>扫描所选 {selected.length} 个相册</button></section></>}</>}
      {page==='connections'&&<><div className="mobile-page-heading"><div><span className="eyebrow">REMOTE LIBRARIES</span><h1>连接 NAS / 电脑</h1><p>独立浏览不同图库，原始素材始终只读</p></div><Network/></div><section className="card mobile-connections"><button className="mobile-library-row" onClick={()=>changeSource('local')}><HardDrive/><span><strong>手机图库</strong><small>本地扫描与统计 · 可离线使用</small></span></button>{connections.map(c=><div className="mobile-connection-card" key={c.slot}><button className="mobile-library-row" onClick={()=>openLogin(c)}><Network/><span><strong>{c.name}</strong><small>{c.url||'填写 NAS 或电脑手机访问地址'}</small></span><ChevronDown size={14}/></button>{c.remembered&&<div className="mobile-connection-footer"><span>已保存登录会话</span><button disabled={busy} onClick={()=>showLogin(c)}>编辑连接</button><button disabled={busy} onClick={()=>act(async()=>{await native('forget',{slot:c.slot});if(connection?.slot===c.slot)changeSource('local');setRefresh(n=>n+1);setNotice('已忘记登录，连接地址保留');})}>忘记登录</button></div>}</div>)}</section><section className="card mobile-scan-status"><ShieldCheck/><h3>连接与数据</h3><p className="helper">保持登录会加密保存会话，不保存密码；会话到期或被服务端撤销后需重新登录。远程访问使用 VPN 或受信任 HTTPS。</p><p className="helper">连接服务端后不会上传手机照片，也不会合并不同图库的统计。</p></section></>}
    </main>
    <nav className="mobile-nav" aria-label="主导航">{[{key:'overview',label:'总览',icon:LayoutDashboard},{key:'gallery',label:'素材',icon:ImageIcon},{key:'scan',label:'扫描',icon:FolderOpen},{key:'connections',label:'连接',icon:Network}].map(({key,label,icon:Icon})=><button key={key} className={page===key?'selected':''} onClick={()=>go(key)}><Icon size={20}/><span>{label}</span></button>)}</nav>
    {picker&&<div className="modal-backdrop" onClick={()=>setPicker(false)}><section className="modal mobile-sheet" role="dialog" aria-modal="true" aria-label="切换图库" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>切换图库</h2><button className="icon-button" aria-label="关闭" onClick={()=>setPicker(false)}><X/></button></div><button className="mobile-library-row" onClick={()=>changeSource('local')}><HardDrive/><span><strong>手机图库</strong><small>只读扫描 · 本地统计</small></span></button>{connections.map(c=><button key={c.slot} className="mobile-library-row" onClick={()=>openLogin(c)}><Network/><span><strong>{c.name}</strong><small>{c.url||'添加连接地址'}</small></span></button>)}</section></div>}
    {login&&<div className="modal-backdrop" onClick={()=>{if(!busy){revision.current++;setLogin(null);}}}><section className="modal mobile-sheet" role="dialog" aria-modal="true" aria-label="连接服务端" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>连接 NAS / 电脑</h2><button className="icon-button" disabled={busy} aria-label="关闭" onClick={()=>{revision.current++;setLogin(null);}}><X/></button></div>{error&&<div className="banner error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();connect();}}><label>连接名称<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>镜迹服务地址<input required type="url" placeholder="http://192.168.1.10:52032" value={address} onChange={e=>setAddress(e.target.value)} autoCapitalize="none"/></label><label>连接密码<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off"/></label><label className="remember-login"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>保持登录（加密保存会话）</label><p className="helper">NAS 使用管理员密码；电脑使用“手机访问 → 连接本机图库”中设置的连接密码。不保存密码，只提供查询和只读扫描，不修改原片或增删目录。</p><button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Network size={16}/>} {busy?'正在验证连接…':'连接并读取图库'}</button></form></section></div>}
    {detail&&<div className="modal-backdrop detail-backdrop" onClick={()=>setDetail(null)}><section className="detail-modal mobile-detail" role="dialog" aria-modal="true" aria-label="素材详情" onClick={e=>e.stopPropagation()}><div className="mobile-detail-top"><span className="eyebrow">ASSET DETAILS</span><button className="icon-button" aria-label="关闭详情" onClick={()=>setDetail(null)}><X/></button></div><Preview item={detail} source={source} detail/><div className="detail-info"><h2>{detail.relpath.split('/').pop()}</h2><p className="filepath">{detail.root_label} / {detail.relpath}</p><div className="detail-tags"><span>{detail.ext.toUpperCase()}</span><span>{bytes(detail.size)}</span><span>{detail.width&&detail.height?`${detail.width} × ${detail.height}`:'尺寸未知'}</span></div><dl>{[['相机',detail.camera],['镜头',detail.lens],['原生焦距',detail.focal_native?`${detail.focal_native} mm`:null],['35mm 等效焦距',detail.focal_equiv?`${detail.focal_equiv} mm`:null],['拍摄时间',detail.taken_at],['ISO',detail.iso],['光圈',detail.aperture],['曝光时间',detail.shutter],['视频时长',detail.duration?`${detail.duration} 秒`:null]].map(([label,value])=><div key={label}><dt>{label}</dt><dd className={value?'':'muted'}>{value||'缺失 / 未记录'}</dd></div>)}</dl>{detail.metadata_error&&<p className="helper">读取异常：{detail.metadata_error}</p>}<p className="helper">只读预览 · 原始素材保持不变</p></div></section></div>}
  </div>;
}
